---
- name: Setup WireGuard VPN, Pi-hole, and Unbound on VPS
  hosts: vps
  become: yes
  vars:
    wireguard_port: 51820
    ssh_port: 43764
    pihole_dns: "127.0.0.1#5335"
    admin_user: "gleb"
    pihole_adlists:
    - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
    - "https://adaway.org/hosts.txt"
    - "https://v.firebog.net/hosts/Easyprivacy.txt"
    - "https://v.firebog.net/hosts/Prigent-Ads.txt"
    - "https://v.firebog.net/hosts/AdguardDNS.txt"
  environment:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_CALLBACK_WHITELIST: profile_tasks
  tasks:

  # Update and install dependencies
  - name: Update package list and upgrade system
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install required packages
    apt:
      name:
      - curl
      - wget
      - ufw
      - unbound
      - wireguard
      - sudo
      state: present

  # Create a new sudo user
  - name: Create a new user with sudo privileges
    user:
      name: "{{ admin_user }}"
      groups: sudo
      append: yes
      shell: /bin/bash
      createhome: yes

  # Configure SSH to disable root login and allow only key authentication
  - name: Secure SSH configuration
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"

  - name: Set SSH to use key-based authentication only
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"

  - name: Restart SSH service
    service:
      name: ssh
      state: restarted

  # Install and configure WireGuard
  - name: Download WireGuard setup script
    get_url:
      url: "https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh"
      dest: "/root/wireguard-install.sh"
      mode: '0755'

  - name: Run WireGuard setup script
    command: "/root/wireguard-install.sh auto"
    args:
      creates: "/etc/wireguard/wg0.conf"

  # Extract WireGuard keys
  - name: Get WireGuard server public key
    command: "cat /etc/wireguard/publickey"
    register: server_public_key
    changed_when: false

  - name: Generate WireGuard client key pair
    command: "wg genkey | tee /root/client_privatekey | wg pubkey > /root/client_publickey"
    args:
      creates: "/root/client_privatekey"

  - name: Get WireGuard client private key
    command: "cat /root/client_privatekey"
    register: client_private_key
    changed_when: false

  - name: Get WireGuard client public key
    command: "cat /root/client_publickey"
    register: client_public_key
    changed_when: false

  # Generate WireGuard Client Configuration
  - name: Generate WireGuard client config file
    copy:
      dest: "/root/wg0-client.conf"
      content: |
        [Interface]
        PrivateKey = {{ client_private_key.stdout }}
        Address = 10.66.66.2/24
        DNS = 10.66.66.1

        [Peer]
        PublicKey = {{ server_public_key.stdout }}
        Endpoint = {{ ansible_default_ipv4.address }}:{{ wireguard_port }}
        AllowedIPs = 0.0.0.0/0, ::/0
        PersistentKeepalive = 25

  # Install Pi-hole
  - name: Install Pi-hole
    shell: "curl -sSL https://install.pi-hole.net | bash"
    args:
      creates: "/etc/pihole/setupVars.conf"

  # Disable all Pi-hole logging
  - name: Disable Pi-hole logging
    command: "pihole logging off"

  - name: Set Pi-hole upstream DNS to Unbound
    lineinfile:
      path: "/etc/pihole/setupVars.conf"
      regexp: '^PIHOLE_DNS_1='
      line: "PIHOLE_DNS_1={{ pihole_dns }}"
    notify: Restart Pi-hole

  # Add ad-blocking lists to Pi-hole
  - name: Add curated adlists to Pi-hole
    command: "pihole -a -l {{ item }}"
    loop: "{{ pihole_adlists }}"

  - name: Update gravity (apply new blocklists)
    command: "pihole -g"

  # Configure Unbound
  - name: Configure Unbound for Pi-hole
    copy:
      dest: "/etc/unbound/unbound.conf.d/pi-hole.conf"
      content: |
        server:
            interface: 127.0.0.1
            port: 5335
            do-ip4: yes
            do-ip6: yes
            do-udp: yes
            do-tcp: yes
            access-control: 127.0.0.0/8 allow
            cache-min-ttl: 3600
            cache-max-ttl: 86400
            num-threads: 4
            msg-cache-size: 128m
            rrset-cache-size: 256m
            hide-identity: yes
            hide-version: yes
            root-hints: "/var/lib/unbound/root.hints"
    notify: Restart Unbound

  - name: Download root DNS server list
    get_url:
      url: "https://www.internic.net/domain/named.cache"
      dest: "/var/lib/unbound/root.hints"

  # Firewall settings
  - name: Enable UFW
    ufw:
      state: enabled
      policy: allow

  - name: Allow SSH access
    ufw:
      rule: allow
      port: "{{ ssh_port }}"
      proto: tcp

  - name: Allow WireGuard port
    ufw:
      rule: allow
      port: "{{ wireguard_port }}"
      proto: udp

  - name: Reload UFW to apply changes
    command: ufw reload

  handlers:
  - name: Restart Pi-hole
    command: "pihole restartdns"

  - name: Restart Unbound
    service:
      name: unbound
      state: restarted
